"""empty message

Revision ID: e4cfb8429738
Revises: add_stats
Create Date: 2020-04-29 15:42:52.447947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_carrier'
down_revision = 'add_stats'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
                    sa.Column('marketId', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=True),
                    sa.Column('distanceToArrival', sa.Float(), nullable=True),
                    sa.Column('haveMarket', sa.Boolean(), nullable=True),
                    sa.Column('haveShipyard', sa.Boolean(), nullable=True),
                    sa.Column('haveOutfitting', sa.Boolean(), nullable=True),
                    sa.Column('otherServices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('updateTime', sa.DateTime(), nullable=True),
                    sa.Column('systemId64', sa.BigInteger(), nullable=True),
                    sa.Column('systemName', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['systemId64'], ['systems.id64'],
                                            name=op.f('fk_carriers_systemId64_systems')),
                    sa.PrimaryKeyConstraint('marketId', name=op.f('pk_carriers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carriers')
    # ### end Alembic commands ###
