"""Add stats 2.0

Revision ID: afb7d82a4836
Revises: 8c77d55f1427
Create Date: 2020-03-31 00:21:32.644436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_stats'
down_revision = 'indexes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('lastupdate', sa.Integer(), nullable=False),
    sa.Column('syscount', sa.Integer(), nullable=True),
    sa.Column('starcount', sa.Integer(), nullable=True),
    sa.Column('bodycount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('lastupdate', name=op.f('pk_stats'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
